apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /data/test
      name: hp-volume
  volumes:
  - name: hp-volume
    hostPath:
      # directory location on host
      path: /data