ENV['VAGRANT_DEFAULT_PROVIDER'] = "virtualbox"
Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        echo "10.0.0.10  k8s-master" >> /etc/hosts
        echo "10.0.0.11  k8s-node-1" >> /etc/hosts
        echo "10.0.0.12  k8s-node-2" >> /etc/hosts
    SHELL
    config.vm.synced_folder ".", "/vagrant" 
    config.vm.define "k8s-master", primary: true  do |master|
      master.vm.box = "bento/ubuntu-18.04"
      master.vm.hostname = "k8s-master"
      master.vm.network "private_network", ip: "10.0.0.10"
      master.vm.provider "virtualbox" do |vb|
          vb.memory = 2048
          vb.cpus = 2
          vb.name = "k8s-master"
      end
      master.vm.provision "shell", path: "scripts/common.sh"
      master.vm.provision "shell", path: "scripts/cp.sh"
    end

    (1..2).each do |i|
  
    config.vm.define "k8s-node-#{i}" do |node|
      node.vm.box = "bento/ubuntu-18.04"
      node.vm.hostname = "k8s-node-#{i}"
      node.vm.network "private_network", ip: "10.0.0.1#{i}"
      node.vm.provider "virtualbox" do |vb|
          vb.memory = 1024 
          vb.cpus = 1
          vb.name = "k8s-node-#{i}"
      end
      node.vm.provision "shell", path: "scripts/common.sh"
      node.vm.provision "shell", path: "scripts/node.sh"
    end
    
    end
  end