apiVersion: v1
kind: Secret
metadata:
  name: backend-mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysql.MYSQL_ROOT_PASSWORD }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysql.MYSQL_PASSWORD }}
  