apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
        app: bookstore
        tier: frontend
  template:
    metadata:
      labels:
        app: bookstore
        tier: frontend 
    spec:
      containers:
        - name: nginx
          image: "quay.io/mromdhani/bookstore-front:v0"
          ports:
          - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: bookstore
    tier: frontend
  ports:
    -  port: 80
      #  nodePort: 32200
       targetPort: 80

