apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
      tier: backend-api
  template:
    metadata:
      labels:
        app: bookstore
        tier: backend-api
    spec:
      containers:
        - name: backend
          image: quay.io/mromdhani/bookstore-backend:v2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-api-configs
            - secretRef:
                name: backend-api-secrets
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "350Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
spec:
  type: ClusterIP
  selector:
    app: bookstore
    tier: backend-api
  ports:  
    - port: 80
      name: http
      targetPort: 8080

