apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mysql
  labels:
    app: mysql  
spec:
  strategy:
    type: Recreate
  replicas:  {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
        app: bookstore
        tier: backend-mysql
  template:
    metadata:
      labels:
        app: bookstore
        tier: backend-mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        imagePullPolicy:  {{ .Values.mysql.pullPolicy }}
        envFrom:
          - configMapRef:
               name: backend-mysql-configs
          - secretRef:
               name: backend-mysql-secrets     
        ports:
          - containerPort: 3306
            protocol: TCP
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
             claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: backend-mysql
spec:
  type: {{ .Values.mysql.service.type }}
  selector:
    app: bookstore
    tier: backend-mysql
  ports:
    - name: http
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.targetPort }}